### ISSUE TITLE
feat: 인증 서버를 구축합니다

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#11]
# 2024.01.07 인증서버 테크스펙

### 요약 (Summary)

토큰과 멤버십을 관리하는 인증 서버를 구축합니다.

### 배경 (Background)

클라이언트를 인증하는 필수 기능을 가진 서버입니다. 다른 서버에서 요청하는 회원정보 조회 API를 효과적으로 서빙합니다.

### 목표 (Goals)

- step1. 인증과 멤버십을 관리합니다.
- step1. JWT 토큰이 발급되고 필터링됩니다.
- step1. 이메일과 회원가입이 가능합니다.
   - 회원정보는 MySQL에 저장합니다.
- step1. 프로필 수정(비밀번호 변경/ 이미지 변경)이 가능합니다.
- step1. Swagger로 API를 작성합니다.

### 목표가 아닌 것 (Non-Goals)

- API Gateway에서 토큰 검증, SNS 로그인은 추후에 개발합니다.
- 이메일 인증은 하지 않습니다.
- 중복 로그인 방지, 성인 인증은 추후에 개발할 예정이나 우선순위가 낮습니다.

### 계획 (Plan)

**JWT Token Generate Sequence Diagram**

```mermaid
sequenceDiagram
    Client->>AuthTokenFilter: 로그인 데이터 request
		AuthTokenFilter->>AuthController:request
		AuthController->>UserService(signIn): SignInRequestDto
		UserService(signIn)->>RDB: 유저정보 조회
		UserService(signIn)->>JwtUtils: UserDetailsImpl
		JwtUtils-->>UserService(signIn): Token Value
		JwtUtils->>Cache: Refresh Token 저장
		UserService(signIn)-->>AuthController: 문자열 토큰 반환
		AuthController-->>Client: JWT

```

1. 클라이언트는 로그인 정보(json)를 서버에 request
2. `OncePerReqeustFilter` 를 extends 한 AuthTokenFilter에서 JWT 쿠키 검증 진행
3. JWT 쿠키가 없으면 FilterChain에 request를 전달해 AuthController로 로그인 데이터 전달
    1. request 데이터(json)는 jackson을 통해 SignInRequestDto 객체로 변환
4. SignInReqeustDto 객체를 UserService의 signIn 메서드에 전달
5. signIn 메서드는 JwtUtils를 통해 토큰을 발급
    1. redis에 refresh token 저장
    2. response의 헤더에 JWT 쿠키 추가

**JWT Token Filtering Sequence Diagram**

```mermaid
 sequenceDiagram
    Client->>AuthTokenFilter: 기능 request
		AuthTokenFilter->>JwtUtils: 토큰 검증
		AuthTokenFilter->> AuthController: 기능 요청
		AuthController-->> Client: 기능 결과 반환
				
```

1. `OncePerReqeustFilter` 를 extends 한 AuthTokenFilter에서 JWT 쿠키 검증 진행
    
    권한이 있고 유효하면 `UsernamePasswordAuthenticationToken` 객체에 회원의 데이터를 저장하고 AuthController에 기능 요청
    
    1. 토큰 유효성 검사
        1. 유효하지 않으면 `AuthenticatoinEntryPoint` 를 extends 한 AuthEntryPoint로 클라이언트에 에러 반환
    2. 회원 권한 검사
        1. 권한이 없으면 `AccessDeniedHandler` 를 extends 한 JwtDeniedHandler로 클라이언트에 에러 반환
        

### 이외 고려 사항들 (Other Considerations)

인증 서버와 유저 서버를 분리할 계획입니다.

### 마일스톤 (Milestones)

~ 1/6: 인증 서버 step1 구축 및 Swagger로 API 문서화

~ 1/12: 인증 서버 완성

**Comment by kor-Chipmunk** [comment]
@happysoy 작업 범위가 크지만, 사전에 이야기 해주신 부분이라 감안하겠습니다..! 다음에는 목표에 적은 내용 중 하나만 해도 되지 않을까 싶네요.

계획에 들어간 부분은 JWT Token 에 한정된 것 같아서, 로그인이나 회원가입, 프로필 수정은 어떻게 되는지 불분명한 것 같아요.
따라서 `JWT 토큰이 발급되고 필터링됩니다.` 부분만 검토하겠습니다.
나머지 부분을 더 채워주시거나, 또는 PR 범위를 계획에 올려주신 부분만 포함해 주세요!

계획에서 `OncePerReqeustFilter` 를 사용하는 이유도 포함되면 좋을 것 같아요. 일단 `Filter` 와 비교해서 어떤 점이 좋아서 사용하는지 들어가면 좋을 것 같아요.

시퀀스 다이어그램에서 데이터를 주고받을 때 형태가 어떤지, 어떤 URL 로 주고 받는지 더 자세하게 포함되면 좋을 것 같아요.
또한 요청과 응답이라는 관점에서 작성하면 더 좋을 것 같아요. `UserDetailsImpl`, `SignInRequestDto`, `Token Value`, `JWT` 은 데이터일 뿐, 흐름을 직접적으로 파악하는 데 도움이 되진 않은 것 같아요.
즉, 시퀀스다이어그램 아래에 부가 설명이 필요 없도록 작성할 수 있으면 좋아요.
충분히 시퀀스다이어그램의 노트나 박스, 통신 Blocking 표시(Activation) 으로 표현 가능합니다.

```mermaid
sequenceDiagram
    Client->>AuthTokenFilter: POST /tokens
    note right of Client: [Header]<br>Authorization: 없음
    note right of Client: { <br> "id": "XXX" <br> "pw": "XXX" <br> }
    note right of AuthTokenFilter: JWT 헤더 없음
    
    AuthTokenFilter->>AuthController:컨트롤러 요청
    AuthController->>+UserService(signIn): 로그인 요청
    note right of AuthController: class SignInRequestDTO {<br>String id<br>String pw<br>}

    box JWT 토큰 발급
        participant UserService(signIn)
        participant RDBMS
        participant JwtUtils
    end
    
    UserService(signIn)->>+RDBMS: 유저정보 조회 요청<br>(ReadOnly Transactional)
    RDBMS-->>-UserService(signIn): 유저 엔티티 응답
    note right of UserService(signIn): class UserEntity { ... }

    UserService(signIn)->>+JwtUtils: 토큰 발급 요청
    JwtUtils-->>-UserService(signIn): 유저 ID 가 담긴 토큰 발급
    note over RDBMS: [Payload]<br>userId = 1
    
    JwtUtils->>Cache: Refresh Token 저장
    note right of JwtUtils: key = {userId}<br>value = {Refresh Token}

    UserService(signIn)-->>-AuthController: 로그인 응답
    note right of AuthController: class SignInResponseDTO { <br> String accessToken <br> String refreshToken <br> }

    AuthController-->>Client: 컨트롤러 응답
    note over AuthTokenFilter: { <br> "accessToken": "XXXXXXXX", <br> "refreshToken": "XXXXXXXX" <br> }

```

시퀀스다이어그램 머메이드 요소 참고 자료 : https://velog.io/@qhflrnfl4324/Mermaid%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%8B%9C%ED%80%80%EC%8A%A4-%EB%8B%A4%EC%9D%B4%EC%96%B4%EA%B7%B8%EB%9E%A8
