### ISSUE TITLE
feat: 플레이리스트 서버를 구축합니다

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#14]
### 요약 (Summary)

회원은 플레이리스트를 생성, 수정, 삭제할 수 있습니다. 생성시 공개범위(비공개, 팔로워만, 전체공개)를 설정할 수 있습니다.

### 배경 (Background)

생성해둔 플레이리스트를 기반으로 채팅 라이브를 진행됩니다.

### 목표 (Goals)

- 플레이리스트 CRUD가 가능합니다.
  - 플레이리스트 정보는 MongoDB에 저장합니다.
  - 플레이리스트 공개 범위는 개인으로 한정합니다.

### 목표가 아닌 것 (Non-Goals)
- 단순 CRUD이므로 시퀀스 다이어그램은 작성하지 않고, API 명세만 작성합니다.
- 재생목록은 추후에 구현합니다.
- 현재 단계에서 여러 회원이 동시에 플레이리스트를 수정할 경우 트랜잭션은 고려하지 않습니다.

### 계획 (Plan)

 추후 작성

### 이외 고려 사항들 (Other Considerations)

추후 작성

### 마일스톤 (Milestones)

추후 작성

**Comment by suakang17** [comment]
플레이리스트 담당자 변경으로 이슈 닫겠습니다.
새로운 테크 스펙은 내일 내로 작성하겠습니다.
