### ISSUE TITLE
feat: 피드 서버를 구축합니다.

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#15]
## 요약 (Summary)
회원은 다른 회원을 팔로우, 언팔로우 할 수 있습니다.

## 배경 (Background)
- 플레이리스트 공개 범위는 비공개, 팔로워에게만 공개, 전체 공개가 있습니다.
- 플레이리스트 피드는 팔로잉한 유저의 플레이리스트로 구성됩니다.

## 목표 (Goals)
- 팔로워/팔로잉 관계를 설정 및 조회합니다.
       
## 목표가 아닌 것 (Non-Goals)
- 마이크로 서비스 간 통신은 고려하지 않습니다. 따라서 유저 데이터는 유저 서비스의 호출 없이 더미데이터로 진행합니다.
- 플레이리스트 피드는 추후에 구현합니다.
- 공통 성공, 예외 응답

### GraphDB 선정
- 팔로워-팔로잉은 RDB에서 Join과 Group By 쿼리를 사용해서 구현할 수도 있습니다.
- 하지만 프로젝트가 음원 스트리밍 + 소셜을 합한 서비스이기 때문에 소셜 시스템과 관련한 부분이 존재합니다.
    - 플레이리스트 피드는 내가 팔로잉한 회원이 생성한 플레이리스트(비공개 제외)로 구성됩니다.
    - 플레이리스트 추천 피드는 내가 팔로잉한 회원의 팔로잉한 회원이 생성한 플레이리스트로 구성됩니다.
    - "친구의 친구를 추천한다"와 같이 관계를 중심으로 데이터 조회가 필요하기 때문에 GraphDB를 선정했습니다.
 
### GraphDB 스키마 초안
- 팔로우 관계와 팔로우 관계 기반의 플레이리스트 탐색에 초점을 맞춰 2개의 Node와 2개의 Relationship으로 구성하려 했습니다.
    - Node(USER{user_id, username}, PLAYLIST{playlist_id, range, created_at, updated_at})
        - range에는 private, follower_only, public 이 있습니다.
        - 플레이리스트 피드의 순서는 PLAYLIST의 update_at을 기준으로 정렬됩니다.
    - Relationship(FOLLOW, USER_PLAYLIST)
    
```mermaid
graph TD;
    USER_A-->|FOLLOW|USER_B;
    USER_A-->|FOLLOW|USER_C;
    USER_B-->|FOLLOW|USER_D;
    USER_A-->|FOLLOW|USER_D;

		subgraph playlist_a
		USER_A-->|USER_PLAYLIST|PLAYLIST_1;
		USER_A-->|USER_PLAYLIST|PLAYLIST_2;
		end

		subgraph playlist_b
		USER_B-->|USER_PLAYLIST|PLAYLIST_3;
		USER_B-->|USER_PLAYLIST|PLAYLIST_4;
		end

		subgraph playlist_c
		USER_C-->|USER_PLAYLIST|PLAYLIST_5;
		end

		subgraph playlist_d
		USER_D-->|USER_PLAYLIST|PLAYLIST_6;
		end
```
- 특정 유저의 팔로우들의 플레이리스트 목록
    - (:USER)-[:FOLLOW]→(:USER)-[:USER_PLAYLIST]→(:PLAYLIST)

이처럼 GraphDB에 Playlist 정보도 다룰까 고민했던 이유는 아래의 글의 영향을 받았기 때문입니다.
https://groups.google.com/g/neo4j/c/m-g_llITLOE?pli=1
이 글에서는 인스타그램 GraphDB를 설계하는데 Media Node를 추가해도 되는지, 추가한다면 User와 Media의 LIKES 관계를 통해 정보를 조회하는 방식이 괜찮은지에 다루고 있습니다. 이에 대한 답변으로 Media를 Node로 다뤄도 괜찮으며 팔로우하는 사람의 최신 미디어를 20개 보고 싶으면 `MATCH (me:User {id:{userid}})-[:FOLLOW]->(u:User)-[:POSTS]->()-[:NEXT*0..20]->(m:Media)
RETURN u, collect(m) as medias` 이런식으로 불러올 수 있다고 합니다.

### GraphDB 스키마 최종
많은 고민 끝에 위의 아키텍쳐로 캠프장님께 피드백을 받았고, 현업에서는 못 본 방식이라는 답변을 받았습니다. 
**따라서 GraphDB에서는 팔로우 관계의 탐색에 초점을 맞춰 1개의 Node와 1개의 Relationship으로 구성하고, 팔로잉 id 목록만 추출하는 방식으로 변경하였습니다.**

## Neo4j를 선정한 이유
- GraphDB의 종류가 다양했고 한국에는 kakao가 만든 S2Graph도 있지만 GraphDB가 레퍼런스가 많아 러닝커브가 적당했습니다.

## 이외 고려 사항들 (Other Considerations)

만약 아무도 팔로잉하지 않았을 경우 플레이리스트 피드는 어떻게 구성되는지 프론트엔드와 이야기를 나눠봤습니다. 그 결과 전체 공개된 플레이리스트 중 랜덤으로 8개, 10개 정도(짝수) 추출해오는 것으로 결정했습니다.

## 마일스톤 (Milestones)
~11/16: 테크스펙 완성

**Comment by kor-Chipmunk** [comment]
그래프데이터베이스라니 흥미진진하군요..!

공식 홈페이지에도 가이드 있으니 참고해보세요!
기존 RDB JPA 구조에서 `@Node`, `@RelationShip` 만 추가된 것 같네요.
링크 : https://spring.io/guides/gs/accessing-data-neo4j/

피드 관련해서 시스템설계기초 책도 참고하면 좋을 것 같아요.
링크 : https://velog.io/@haron/%EA%B0%80%EC%83%81-%EB%A9%B4%EC%A0%91-%EC%82%AC%EB%A1%80%EB%A1%9C-%EB%B0%B0%EC%9A%B0%EB%8A%94-%EB%8C%80%EA%B7%9C%EB%AA%A8-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%84%A4%EA%B3%84-%EA%B8%B0%EC%B4%88-11%EC%9E%A5-%EB%89%B4%EC%8A%A4-%ED%94%BC%EB%93%9C-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%84%A4%EA%B3%84-i6re3cjt
