### ISSUE TITLE
feat: 음원 서버를 구축합니다.

### ISSUE THREAD

**Issue by kor-Chipmunk** [sgdevcamp2023/sgwannabe#17]
### 요약 (Summary)

음원, 아티스트, 앨범 정보를 관리하는 서버를 구축합니다.
음원의 정보, 아티스트 상세 정보, 앨범 상세 정보를 담당합니다.

### 배경 (Background)

음원과 연결된 정보들 (음원, 아티스트, 앨범) 관리를 한 서버에 구축합니다.
서로의 연관성이 깊기에 별도의 서버로 분리하지 않고 음원 서버로 처리하고자 합니다.
데이터의 필드가 변경되지 않고, 정합성이 중요하기에 RDBMS 구조로 저장합니다.
RDBMS 는 논블록킹 요청이 되지 않아, WebFlux 구조 대신 MVC 구조로 구축합니다.
비동기, 논블록킹을 극대화하는 Kotlin 의 Coroutine 또한 적용할 여지가 없으므로, Java 21 버전을 사용합니다.

### 목표 (Goals)

- MySQL8 도커 연동
- 음원 / 아티스트 / 앨범 CRUD 작성
- 테스트 코드 작성

### 목표가 아닌 것 (Non-Goals)

- 음원 업로드 : 파일 서버와 통신하는 부분은 이번 작업 범위에 포함하지 않습니다.
- 좋아요 구현 : 좋아요 구현은 인증 서버와 연동

### 계획 (Plan)

음원 / 아티스트 / 앨범 엔티티 데이터는 다음과 같습니다.

```mermaid
classDiagram
    class SoundSource {
        Long id
        String title
        String url
        String lyrics
        FileType fileType
        int playTime
        LocalDateTime createdAt
        LocalDateTime updatedAt

        Long likeCount
        Artist artist
        Album album
        List<Artist> composers
        List<Artist> lyricists
    }

    class Artist {
        Long id
        String name
    }

    class Album {
        Long id
        String name
        String coverURL
    }
```

### 마일스톤 (Milestones)

1/9 (화)
- 프로젝트 생성
- 엔티티 작성
- CRUD 작성

1/10 (수)
- 도커 구축
- 테스트 코드 작성

**Comment by happysoy** [comment]
수고하셨습니다! 테스트 코드 작성을 목표로 선정하셨군요. TDD 실천하시는건가요? 대단합니다! 인증 서버와 연동 관련해서 곧 이야기 나눠봐요. 제가 지금 인증서버와 유저서버를 분리했기 때문에 유저서버를 개발하려면 통신 방법을 확정 지어야 해서 어떻게 통신할지 빠른 시일 내에 결정하면 좋을 것 같아요.

**Comment by kor-Chipmunk** [comment]
PR 에 업로드된 클래스 다이어그램 반영합니다.

```mermaid
classDiagram
    class Music {
        Long id
        String title
        Short playTime
        String lyrics
        MusicFile file
        Long albumId
        Long artistId
        LocalDateTime createdAt
        LocalDateTime updatedAt
    }

    class MusicFile {
        String fileUrl
        FormatType formatType
    }

    class Artist {
        Long id
        String name
        GenderType gender
        ArtistType type
        String agency
        LocalDateTime createdAt
        LocalDateTime updatedAt
    }

    class Album {
        Long id
        String title
        AlbumType type
        Long artistId
        LocalDateTime releasedAt
        String coverURL
        LocalDateTime createdAt
        LocalDateTime updatedAt
    }
```
