### ISSUE TITLE
feat: Mopidy를 활용한 스트리밍 미디어 서버를 구축합니다.

### ISSUE THREAD

**Issue by suakang17** [sgdevcamp2023/sgwannabe#19]
### 요약 (Summary)

파일 서버에 저장된 음원을 클라이언트의 요청에 따라 전송하는 스프링부트 Mopidy 스트리밍 미디어 서버를 구축합니다.

### 배경 (Background)

파일 서버의 리소스를 효율적으로 클라이언트에 전달하기 위함입니다.
스트리밍-미디어 서버를 자체적으로 구축하는 것은 시간, 능력상 무리로 느껴져 Mopidy를 적용하기로 하였습니다.

### 목표 (Goals)

- 사용자의 음원 재생 요청에 대한 스트리밍 서비스를 제공합니다.
    - 음원 요청은 HTTP로 이루어집니다.
    - 음원은 스트리밍 형태 또는 HLS(Hypertext Transfer Protocol Live Streaming)로 응답합니다.
    - 요청과 응답은 Springboot 서버를 통해 전달되어집니다.
    - 음원 스트리밍은 Mopidy 미디어 서버를 통해 처리됩니다.

### 목표가 아닌 것 (Non-Goals)

.

### 계획 (Plan)

미디어 서버 오픈소스 후보로는 Iris, Mopidy, Koel이 있었으며 아래는 최종적으로 Mopidy가 선정된 이유입니다.

스트리밍 서버의 요구사항은 다음과 같습니다.

1. 파일 서버에 저장된 음원을 웹 브라우저 플레이어 상에서 스트리밍
2. 압축(인코딩)된 동영상 파일을 미디어 서버로 전송하여 해석(디코딩)하고, 사용자가 볼 수 있게 재포장(압축)하여 클라이언트 플레이어에 전송
3. 스프링 부트 기반 개발
4. HTTP Live Streaming (HLS) 프로토콜 사용

조사한 결과 각 후보군의 특징은 다음과 같습니다.

Iris:

- Spotify Web Player 모방한 UI
- Mopidy기반이므로 웹에서 Mopidy를 효과적으로 관리 가능

Mopidy:

- 확장성 (음악 서버로써 다양한 플러그인 지원)
- Spotify, SoundCloud, Google Music 등 다양한 음악 스트리밍 서비스 통합 가능
- 음악 컬렉션을 효과적으로 관리하고 다양한 음악 스트리밍 서비스를 통합하여 사용하려는 경우 적합

Koel:

- 개인 뮤직 라이브러리를 중심으로 한 음악 플레이어 및 라이브러리
- 설정이 간단하고 사용이 쉽다.

Iris, Koel은 개인 뮤직 라이브러리 위주였고, Mopidy가 압도적으로 문서가 잘되어있으며 Python으로 작성되어있기에 Mopidy이 가장 적합하다고 판단하여 결정하였습니다!

계획은 다음과 같습니다.
클라이언트 요청에 따라 음원을 가져와 스트리밍 하기 위해 Mopidy의 `Mopidy-HTTP` 플러그인을 사용하고, 클라이언트와의 통신을 위해 Mopidy의 `JSON-RPC API`를 활용할 예정입니다.

1. **`Mopidy-HTTP` 플러그인 설치:**
    - `Mopidy-HTTP` 플러그인은 HTTP를 통해 Mopidy에 접근할 수 있는 기능을 제공합니다.
    - 개발 환경 통일을 위해 도커 이미지를 사용합니다.
2. **Mopidy 설정 파일 수정:**
    - Mopidy 설정 파일에 `Mopidy-HTTP` 플러그인을 활성화합니다.
    - 클라이언트에서 요청할 수 있는 포트 및 경로 등을 설정합니다.
3. **`JSON-RPC API` 사용:**
    - `JSON-RPC API`를 통해 Mopidy를 제어합니다.
    - **`core.playback.stream`** 클라이언트에서 원하는 음원 스트리밍
4. **클라이언트 요청 처리:**
    - 클라이언트의 HTTP 요청을 처리하고, 필요한 `JSON-RPC API`를 호출하기 위해 Springboot 서버를 구성합니다.

### 이외 고려 사항들 (Other Considerations)

None.

### 마일스톤 (Milestones)

~1/12 (금) API 명세 완성, 아키텍처 확정, 개발 환경 구축
~1/15 (월) 파일서버 API 엔드포인트 작성
~1/17 (수) 클라이언트 API 엔드포인트 작성

**Comment by kor-Chipmunk** [comment]
스트리밍 서버가 저한테 옮겨져서 이 이슈는 닫을게요!
새 스트리밍 서버 테크 스펙 내일 중으로 작성하겠습니다.
