### ISSUE TITLE
feat: 프론트엔드 프로젝트 개발 환경 세팅

### ISSUE THREAD

**Issue by mingzooo** [sgdevcamp2023/sgwannabe#2]
### 요약 (Summary)

`src/frontend` 안에 프론트엔드 개발 환경을 세팅합니다.

### 배경 (Background)

중간에 도입하는 것보다 초기에 세팅을 완료한 채로 이후에는 화면 구현에 집중할 수 있게끔 미리 정리해 놓으려고 합니다.

### 목표 (Goals)

- React
- Typescript
- Tanstack-Query (React-Query)
- Recoil
- styled-components
- eslint, prettier

### 계획 (Plan)

- 코드컨벤션에 따른 폴더 및 파일 세팅
- 패키지 설치

### 마일스톤 (Milestones)

1/3 
- 코드 컨벤션 확립

1/4 
- 폴더 및 파일 구조 세팅
- 컴포넌트 페이지 구조 세팅

1/5 
- 상태관리 패키지 세팅
- 문서화
- PR

**Comment by kor-Chipmunk** [comment]
Merge 되어서 이슈 닫을게요.
