### ISSUE TITLE
fix: 컴포넌트 스타일링 라이브러리 수정 (styled-components => tailwind CSS)

### ISSUE THREAD

**Issue by mingzooo** [sgdevcamp2023/sgwannabe#20]
### 요약 (Summary)

css 라이브러리를 [styled-components](https://styled-components.com/) 에서 [tailwind CSS](https://tailwindcss.com/)로 변경합니다.

### 배경 (Background)

컬러시스템과 타이포그래피 시스템을 구현하여 메인페이지 퍼블리싱하다가 styled-components의 한계점을 마주치게 되었습니다.

문제점
- 디자인 시스템을 위한 부가적인 코드가 실제 기능 코드를 침범한다.
- 기능 코드와 파편화되어 추가 비용을 발생시킨다 (Styled-Component)
- 디자인 시스템을 구현하는 데에 있어 styled-component에서 용이하지 못함을 느꼈습니다.
- styled-component는 이름에 붙은 것처럼 컴포넌트 단위로 구성하다 보니 css 속성을 두개정도 가지고 있을 때, 컴포넌트로 분리하는 것에 대한 의문이 많이 들었습니다.

### 목표 (Goals)

- 기존의 스타일링을 tailwind CSS로 전환합니다.
- tailwind CSS를 사용해서 디자인 시스템을 설계합니다.
- 해당 프로젝트에 맞는 tailwind의 효율적인 사용 방식을 확립합니다.

### 계획 (Plan)

**리서치/사용 tailwind의 장점**

- 네이밍 시간 단축
- 타이포그래피 시스템과 같은 디자인 시스템 구축에 용이함 (유지보수 관점에서 수정에 용이)
- 해당 태그가 어떻게 생겼을지 예측 가능
- 코드 파편화 해결
- 다해상도 대응

---
메인 참고 자료
[Tailwind CSS 사용기](https://fe-developers.kakaoent.com/2022/220303-tailwind-tips/)
[FE개발그룹에서는 Tailwind CSS를 왜 도입했고, 어떻게 사용했을까?](https://fe-developers.kakaoent.com/2022/221013-tailwind-and-design-system/)

### 마일스톤 (Milestones)

1/8 : 테일윈드 리서치
1/9 : 테일윈드 도입 및 기존 코드 수정
1/10 : tailwind를 사용해보고 난 후, 효율적인 방식에 대한 리서치
1/11 : styled-component 완전 제거
~1/12 : 디자인시스템, 타이포그래피 구현

**Comment by kor-Chipmunk** [comment]
피드백 때 말씀하신대로 불필요한 컴포넌트를 만들지 않아도 되고, 미리 지정된 형식으로 빠르게 개발할 때 좋은 것 같네요!

궁금한 점이 러닝 커브가 꽤 있을 것 같은데 이를 극복하기 위한 계획이 있으실까요?

또한 세 번째 목표는 효율적인 사용 방식에 대한 고민, 후기, 회고 같은게 나오는 걸까요??

**Comment by mingzooo** [comment]
@kor-Chipmunk 
선재님 의견 감사합니다!
러닝커브때문에도 사실 초반에 고민이 많았는데요. 그래서 처음에는 tailwind를 안쓰려고 했는데, 구현을 계속하다보니 너무 비효율적이다는 생각이 많이 들어서 도입을 결심하게 되었습니다!
일단 몇 일 사용해본 결과, 단순 구현은 러닝커브가 그렇게 심하지 않아서 적응한 상태입니다.
근데 처음 써보다보니 tailwind를 잘쓰고 있나라는 의문이 들더라구요.
물론 정답은 없겠지만, 해당 프로젝트에 가장 적합한 방식을 찾고싶어서 노력하고있습니다! -> 이렇게 고민해서 찾은 결과는 블로그에 작성하면 너무 좋지 않을까 생각해서 계획하고 있습니다
근데, 이 방식에 대한 고민 시간이 지금까지도 많이 소요됨을 느껴서 일단 구현하고 리팩토링으로 효율성을 높여보는 방식으로 고려하고있습니다!
