### ISSUE TITLE
feat: 회원가입을 구현합니다.

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#22]
### 요약 (Summary)

유저 서버는 클라이언트의 회원가입 요청을 수행합니다.

### 배경 (Background)

회원가입을 통해 회원의 정보를 서버에서 관리할 수 있습니다.

### 목표 (Goals)

- 클라이언트의 이메일과 비밀번호를 저장하는 자체 회원가입 방식을 구현합니다.
- 이메일 인증을 진행합니다.

### 목표가 아닌 것 (Non-Goals)

- Oauth는 추후에 개발합니다.
- Gateway를 통한 라우팅은 추후에 구현합니다.
- 성인인증은 추후에 개발할 계획이나 우선순위가 낮습니다.

### 계획 (Plan)

- 이메일 인증은 회원가입 시 진행합니다.
    - 회원가입 후 이메일 인증을 진행해 유저의 권한을 활성화시키는 방식은 여러 이슈가 발생하게 됩니다.
        - 유효한 인증 시간이 지나면 인증을 다시 보내는 로직이 필요합니다.
    - 빠른 개발을 위해 회원가입 시 이메일 인증을 받고 회원가입이 완료된 유저의 모든 권한을 활성화하는 방식으로 구현하였습니다.
- 이메일 인증은 OTP 번호를 만들어 인증 코드를 입력하는 방식으로 구현합니다.
    - 인증 코드는 expired되는 특성을 가지고 있기 때문에 TTL 설정과 함께 redis에 저장합니다.
    - 회원가입 요청 시 body에 있는 정보를 회원DB에 추가합니다.
    - 회원 관련 정보는 데이터의 정합성이 중요하기 때문에 DB로 MySQL을 선정하였습니다.

- ERD 설계
<img width="870" alt="image" src="https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/54467323-3dd1-453e-8280-7952eaf6092c">

- API 명세

Method | REST API | Description
-- | -- | --
POST | v1/user-service/email | 이메일 인증 코드 전송
POST | v1/user-service/verification | 이메일 인증 코드 검증
POST | v1/user-service/signup | 회원가입

<pre><code class="language-json"># 성공 응답 200 OK
{
    "success": true,
    "status": 200,
    "data": {
        "message": "회원가입에 성공했습니다"
    },
    "date_time": "2024-01-14T01:13:11.682607"
},
{
    "success": true,
    "status": 200,
    "data": {
        "message": "인증코드가 일치합니다"
    },
    "date_time": "2024-01-14T01:13:27.718663"
}

# 실패 응답 - 400
{
    "success": false,
    "status": 400,
    "code": "206",
    "reason": "이미 사용 중인 이메일입니다",
    "date_time": "2024-01-14T01:14:14.160397",
    "path": "/v1/user-service/email"
},
{
    "success": false,
    "status": 400,
    "code": "207",
    "reason": "인증코드가 유효하지 않습니다",
    "date_time": "2024-01-14T01:15:26.104587",
    "path": "/v1/user-service/verification"
},
{
    "success": false,
    "status": 400,
    "code": "208",
    "reason": "메일 전송 중 에러가 발생했습니다",
    "date_time": "2024-01-14T01:15:26.104587",
    "path": "/v1/user-service/email"
},
# 실패 응답 - 500
{
    "success": false,
    "status": 400,
    "code": "206",
    "reason": "서버에 에러가 발생했습니다",
    "date_time": "2024-01-14T01:17:36.386621",
    "path": "/v1/user-service/signup"
}

</code></pre>

### 이외 고려 사항들 (Other Considerations)

- 메일 전송 처리는 동기/ 비동기가 있지만 현재 단계에서는 동기 방식으로 구현합니다.

- 프론트엔드가 API를 수월하게 볼 수 있도록 swagger로 API를 관리하는 방식을 채택했었지만 배포되지 않았기 때문에 프론트엔드가 localhost에서 실행시켜봐야 한다는 번거로움이 있어 API는 표로 관리해 전달하는 방식으로 결정했습니다.
  - 초반에 활용했던 swagger
<img width="1710" alt="스크린샷 2024-01-11 오후 6 58 59" src="https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/b3b17563-e096-442d-be8d-75d80e66c0e1">
<img width="1710" alt="스크린샷 2024-01-11 오후 6 59 38" src="https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/f69e1777-47df-4632-a662-073b18545911">

### 마일스톤 (Milestones)

1/11~1/13: 회원가입 완성

**Comment by kor-Chipmunk** [comment]
오우 고생하셨어요!! 낼 ERD 같이 한 번 보져!

**Comment by kor-Chipmunk** [comment]
@happysoy 앗, 오늘 깜빡하고 ERD 이야기를 못 나눴네요 ㅠㅠㅠ
하고싶었던 이야기가 있었는데 아래에 짤막하게 적어둘게요!

## 1. 유저 번호 필드 : `number` -> `id` 제안
고유키를 보통 `id` 라고 짓는게 일반적이라 '숫자' 라는 의미의 `number` 보단 `id` 로 하는 게 어떨까 제안드려요!

## 2. 유저 이름 `username` 변경 제안

필요한 게, `김선재` 같은 본명을 원하는 건지, `다람쥐` 같은 닉네임을 원하는 건지 파악이 안되는 것 같아요!
또한 앞에 `user` 가 테이블명과 중복되어 있어서 제거해도 괜찮지 않을까 싶습니다.

`name` 인지 `nickname` 인지만 구분해두면 좋을 것 같아요!
멜론 기준으로는 카카오 로그인할 때 이름을 가져오지만, 수정할 수 있는 걸로 알고 있어요.
따라서 범용성 있는 닉네임으로 두는 건 어떨까 생각되네요.

참고로, 한글, 영문, 숫자, 일부 특수문자(`-`, `_`, `.`) 만 사용 가능하고 최대 15자까지 입력이 가능해요.
왜 일부 특수문자만 가능하게 헀을까, 는 궁금하긴 하네요. ( 다른 특수문자는 보기에 예쁘지 않을수도!? )

## 3. 비밀번호 길이
비밀번호 길이가 60 으로 고정되어 있는데, 혹시 비밀번호 암호화할 때 어떤 암호화 종류인지 여쭤봐도 괜찮을까요~?
스프링 시큐리티 등에서 기본으로 제공하고 있는 게 뭔지, 또 다른 암호화를 생각하고 있으신 게 있는지 궁금해요.

## 4. 이메일 길이
이메일 길이에 관한 논의가 있었는데 소연님은 어떻게 생각하는지 궁금해요.
@ 앞 파트는 64글자, 도메인 파트는 254 글자, 총 제한은 256 글자라고 하네요.
참고 링크 : https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
캠프장님 말씀처럼 굳이 그렇게 길게 잡지 않아도 되기도 하고, 크게 중요하지 않다 싶으면 넉넉하게 50~60 정도로 잡아도 괜찮을 것 같아요.

## 5. 유저 상태 `status` 타입 `tinyint` 으로 제안
`status` 가 0 (활성화), 1 (비활성화), 2 (탈퇴) 로 되어 있는데 `boolean` 형으로 되어 있어서 `tinyint` 으로 되어야할 것 같아요.

번외로 DB 상에서 저는 어떤 값인지 바로 확인하려고 문자열로 적는 편인데, 소연님처럼 `tinyint` 로 적는 게 좋을까요, 문자열로 관리하는 게 좋을까요!? 현업에선 어떻게 하는 게 표준일까요, 이런 주제가 떠오르네요. ( fyi. @sgdevcamp )

## 6. profile `json`
JSON 타입 좋습니다. 👏👍
JSON { } 가 두 개가 있는데, 프로필을 여러 개 가지는 걸 생각하고 계시는 걸까요?
여러 개면은 아래처럼 대괄호를 붙여야 할 것 같아요.

```json
[
    {
        ...
    },
    {
        ...
    }
]
```

## 7. NULLABLE / DEFAULT VALUE

필드가 널이 들어가는지, 널이 들어가지 않는지, 기본값은 있는 건지 궁금해요.
`role` 로 예를 들면 당연히 기본 값은 `1` 일반 유저 이겠지만, 사소한 것도 짚고 넘어가면 좋을 것 같아요.
아래는 제가 에이쿼리로 짰던 예시입니다!

![스크린샷 2024-01-13 오전 1 34 27](https://github.com/sgdevcamp2023/sgwannabe/assets/16275188/1dddb96a-ccc8-49c6-acf7-43fefa6cb082)

참고로, 에이쿼리는 잘 만들어줄 SQL 문이 필요해서 이용 했었어요. 테이블 5개 넘어가면 유료니.. 
대충 포맷만 빼와서 나중에 SQL 문으로 보충할 것 같아요.

## 8. 인덱싱

DB 인덱싱에 대한 고민도 해보면 좋을 것 같아요.
DB 조회 퍼포먼스를 향상시키는 기본적인 거라, 어떤 키로 많이 조회할 건지에 대한 고민도 들어가면 좋을 것 같습니다.

## 9. 최근 접속 시간

피드백 들었던 사항 중, `최근 접속 시간`도 들어가면 좋을 것 같아요.

**Comment by happysoy** [comment]
헉.... 선재님..... 감동입니다... 피드백 120% 반영하도록 하겠습니다!
![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/ae8ca8f8-106a-42c9-b443-f5e21aca329d)

**Comment by happysoy** [comment]
### 1. 유저 번호 필드

id로 변경했습니다! 

### 2. username 변경

말씀하신 것처럼 nickname이 더 범용성이 있네요. username으로 변경했습니다!

그런데 말씀하신 `한글, 영문, 숫자, 일부 특수문자(-, _, .) 만 사용 가능하고 최대 15자까지 입력 가능` 부분이 잘 이해가질 않습니다. columnDefinition으로 컬럼타입을 한글, 영문, 일부 특수문자만 가능하도록 설정을 해야한다는 걸까요? 그렇다면 해당 부분은 프론트엔드 영역에서 처리해야 하는 영역이 아닌가 싶습니다!

### 3. 비밀번호 길이

개인과제에서는 솔트 기법과 SHA-256 해시 알고리즘을 사용해 단방향 암호화를 직접구현하였습니다만, 아무래도 직접 구현한 건 보안에 취약하겠다는 생각에 Spring Security Crypto를 사용해 암호화를 구현했습니다.

그중 bcrypt는 password encoder의 기본 전략일정도로 강력한 해싱함수이기 때문에 ERD를 설계할 때는 bcrypt을 사용하기 위해 **char(60)**으로 설정했습니다.

다만 구현을 하면서 다음과 같은 생각이 들었습니다.

- 만약 서버가 해싱 알고리즘을 바꾸게 된다면?
    - 기존 회원의 비밀번호 암호화에 bcrypt를 사용했다가 서버의 해싱 알고리즘을 바꾸게 된다면 기존 회원이 비밀번호를 알맞게 입력해도 해싱값이 달라지면서 로그인을 하지 못하는 문제가 발생하게 됩니다.

예를 들어 현재 서버가 SHA-256 알고리즘을 사용하고 있는데 bcrypt로 마이그레이션하는 방법에 대해서는 아래 글에서 다루고 있습니다.

참고링크: https://www.baeldung.com/spring-security-5-password-storage

마이그레이션시 발생하는 문제를 해결하기 위해 저는 PasswordEncoder를 인터페이스로 만들어 변화에 유연하게 대응하도록 했습니다. 

```
UserConfig.java

@Configuration
public class UserConfig {
    @Bean
    public PasswordEncoder passwordEncoder() {
        DelegatingPasswordEncoder passwordEncoder = (DelegatingPasswordEncoder) PasswordEncoderFactories.createDelegatingPasswordEncoder();
        passwordEncoder.setDefaultPasswordEncoderForMatches(new BCryptPasswordEncoder());
        return passwordEncoder;
    }
}
```

서버가 해싱 알고리즘을 변경하는 경우 대응하는 방법은 다음과 같습니다. createDelegatingPasswordEncoder() 정적 메서드로 생성된 DelegationPasswordEncoder는 암호화 시 bcrpyt를 사용합니다. 해당 구현체로 비밀번호를 암호화 하면 `{bcrypt}$2a$10$.AODvZL` 이런 식으로 사용한 알고리즘에 대한 접두사가 붙게 됩니다. 따라서 해당 접두사를 통해 서버가 해싱 알고리즘을 변경하더라도 기존 DB에 저장되어 있던 비밀번호와 호환성을 지킬 수 있게 되는 것입니다.

비밀번호는 bcrpyt 알고리즘으로 암호화하여 60bytes 로 생성되지만 사용한 알고리즘에 대한 접두사가 붙으므로 추가적인 byte가 필요합니다. 
![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/cf4dce9e-bde7-4661-aa42-edf231ab1922)

따라서 비밀번호 타입은 **char(68)**로 설정하였습니다!

### 4. 이메일 길이

stackoverflow 링크 첨부 감사합니다! 흥미로운 논의네요. 전 넉넉하게 varchar(60)으로 잡겠습니다.

### 5. 유저 상태 status 타입

앗 boolean으로 잘못 적었었네요..! 피드백 감사합니다!
제가 tinyint로 지정한 이유는 enum으로 관리할 수 있는 부분을 DB에 string으로 저장하면 데이터가 많아질 경우 메모리 용량을 잡아먹는다고 생각했기 때문입니다. 

현업에서는 어떤 방식을 사용하는지 찾아보다가 다음 글을 발견했는데 공유드려요~!
참고링크: https://techblog.woowahan.com/2527/

![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/3121ff73-a983-4d13-b379-2dc8ba63d761)
enum 선언 후 DB에는 string으로 저장하고 있네요!

### 6. Profile Json

캠프장님께서 피드백 주신대로 프로필 상태메시지와 history를 조회하는 기능을 생각해봤습니다. 그래서 프론트엔드와 논의해봤는데 아무래도 시간이 촉박하다보니 해당 기능은 구현이 어려울 것 같아 프로필은 한개만 가지는 방식으로 구현하기 위해 대괄호를 제외했습니다. 🙂
다만 프로필 url, update_at 필드는 가져가면서 테이블은 새롭게 만들지 않기 위해 json 타입을 선택했습니다!

### 7. NULLABLE / DEFAULT VALUE
이 부분도 기재를 했어야 했는데 깜빡했네요. 수정해서 올리도록 하겠습니다.

### 8. 인덱싱
해당 부분 고민 후 테크스펙에 내용 추가하도록 하겠습니다.

### 9. 최근 접속 시간
필드 추가했습니다!
