### ISSUE TITLE
feat: 로그인 페이지 퍼블리싱

### ISSUE THREAD

**Issue by mingzooo** [sgdevcamp2023/sgwannabe#24]
### 요약 (Summary)

로그인 화면을 구현합니다.

### 배경 (Background)

서비스의 유저가 로그인을 할 수 있는 페이지입니다.
추후 로그인 api 연동을 위한 페이지 입니다.

### 목표 (Goals)

- 로고 제작
- 로그인 화면 퍼블리싱

### 목표가 아닌 것 (Non-Goals)

- react-hooks form 도입
- api 기능 구현 : 로그인
- 페이지 라우팅

### 계획 (Plan)

- 아이디, 비밀번호 컴포넌트가 중복되기 때문에 하나로 만들어 props로 데이터 전달하여 재사용할 것입니다.
- 자체 로그인, 카카오 로그인으로 컴포넌트 하나로 재사용

### 마일스톤 (Milestones)

1/11 : 로그인 퍼블리싱
1/12 : 테크스펙 작성 및 pr 올리기

**Comment by kor-Chipmunk** [comment]
로고 제작까지 못하는 게 없으시군여 🥹🥹 응원합니다!

**Comment by mingzooo** [comment]
PR 완료로 이슈 닫겠습니다!
