### ISSUE TITLE
feat: 자체 로그인, 로그아웃을 구현합니다.

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#27]
## 요약 (Summary)
- 클라이언트의 로그인 요청에 따라 Access Token과 Refresh Token을 발급합니다.
- 인증 서버에서는 로그인과 로그아웃 기능을 수행합니다.

## 배경 (Background)
클라이언트를 인증하는 필수 기능을 가진 서버입니다. 자체 로그인이란 Oauth 로그인과 달리 이메일, 비밀번호로 로그인하는 것을 의미합니다.

## 목표 (Goals)
- 로그인 정보가 DB와 일치하면 Refresh Token을 캐시에 저장하고 Access Token과 Refresh Token을 HTTP 헤더의 쿠키에 담아서 클라이언트에게 보냅니다.
- 로그아웃 요청시 캐시에 담긴 Refresh Token을 삭제합니다.
  
## 목표가 아닌 것 (Non-Goals)
- Redis Master Slave 구성은 현재 단계에서 구현하지 않습니다.
- Gateway 사용 여부는 팀 회의를 통해 결정합니다.
- 블랙리스트는 현재 단계에서 고려하지 않습니다.
### 토큰 기반의 인증 방식을 선택한 이유
1. 세션은 stateful한 특성 때문에 scale out에 적합하지 않습니다.
    - stateful한 특성이란 서버 1에서 유저1~유저100 정보를 관리한다고 할때, 유저1을 인증하기 위해서는 HTTP 요청이 반드시 서버1로 가야하는 것을 의미합니다.
    - 트래픽이 증가에 대응하여 scale out하게 되면 stateful 아키텍쳐에서는 문제가 발생합니다. 서버1부터 서버5까지 scale out 했을 때 서버1의 HTTP 요청이 반드시 서버 1로 가야하는데, 반드시 간다는 보장이 없습니다.
    - 다중 서버 환경에서 stateful 문제점을 해결하기 위한 방안들이 여럿(세션 클러스터링, 스티키 세션, 세션 스토리지 분리) 있긴 하지만 stateless한 토큰을 사용하면 간단하게 이 문제를 해결할 수 있습니다.
2. 토큰을 발급하는 OAuth 로그인 방식을 도입할 예정입니다.

### 아키텍쳐
![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/4a877c57-90ae-4b16-9896-fc3d41d09ba3)

- 캐시는 Master-Slave구조로 여러대의 복제본을 만들 수 있는 redis를 사용하였습니다.
- 인증 서비스와 유저 서버스를 분리하였습니다.
    1. 실서비스에서는 특정 시간대에 유저 서비스보다 인증 서비스에 대한 트래픽이 많이 발생하게 됩니다. 두 서비스를 분리해놓는다면 인증 서버만 scale out하여 대응할 수 있습니다.
    2. 또한 인증 서버는 다양한 형태의 클라이언트(app)와 붙을 수 있기 때문에 인증 서버에서는 인증 관리 기능만 처리하도록 하였습니다. 

- 인증 캐시에는 Refresh Token을 저장합니다. 캐시에서 토큰을 관리하는 이유는 다음과 같습니다.
    1. Refresh Token의 호출 빈도가 높다.
        Access Token의 갱신 주기는 보안을 위해 짧게 설정하는데 갱신할 때 마다 Refresh Token을 읽어와야 합니다. DB는 읽기 요청 cost가 크기 때문에 cache에 보관함으로써 병목현상도 방지할 수 있습니다.
    2. Refresh Token 데이터는 expired 되는 특성이 있다.
        DB에 expired 된 데이터를 저장해두고 있는건 비효율적입니다. Daemon을 통해 불필요한 데이터를 삭제하는 방법도 있지만, 캐시에 TTL 설정을 통해 토큰이 자동으로 삭제되도록 함으로써 데이터를 효율적으로 관리할 수 있습니다.

### 명세서
- 기능: 클라이언트의 로그인 요청을 처리하고 토큰을 발급합니다.
   - 인증서버에서 body를 토대로 회원DB에서 로그인 정보가 맞는지 확인합니다.
   - 인증서버에서 Access Token과 Refresh Token을 발급하고, Refresh Token은 캐시에 저장합니다. 
   - 인증서버에서 두개의 토큰을 클라이언트에게 전달합니다.

### 시크릿 키 생성
비밀키는 아래와 같은 코드로 랜덤하게 생성할 수 있습니다.
`SecretKey key = Jwts.SIG.HS256.key().build();`

하지만 만약 gateway를 도입하게 된다면 auth-server와 api-gateway는 같은 시크릿 키를 가지고 있어야 합니다.
따라서 직접 만든 문자열을 암호화해서 application.yml에 저장한 후 아래와 같은 방식으로 값을 불러오는 방식을 채택했습니다.
```
@Value("${jwt.secret-key}")
    private String secretKey;
```
SignatureAlgorithm으로 HS512(HMAC using SHA-512)를 사용하였습니다.
JWT에서 사용하는 기본 서명 알고리즘의 종류는 13개가 있습니다. 3개의 시크릿 키 알고리즘과 10개의 비대칭키 알고리즘인데, 비대칭키 알고리즘은 저번에 들었던 기본교육에서 인증서 암호화에 사용된다고 들었습니다. 따라서 3개의 시크릿 키 중 HS256과 HS512를 고민했는데 보안 수준은 비슷한 것 같습니다. 차이점이라면 해싱 속도가 어디서 더 빠르냐 정도인것 같습니다.
- HS256 vs HS512
    - SHA-512 is faster than SHA-256 on 64 bit machines
    - SHA-256 is faster than SHA-512 on 8, 16 and 32 bit machines.
https://stackoverflow.com/questions/18080445/difference-between-hmacsha256-and-hmacsha512
https://crypto.stackexchange.com/questions/53826/hmac-sha256-vs-hmac-sha512-for-jwt-api-authentication

HS512 알고리즘을 사용하기 위해서는 secret key가 64byte(512bit) 이상이어야 합니다. 터미널에서 아래와 같이 임의로 정한 문자열을 base64 인코딩한 후 application.yml 파일에 입력했습니다. 물론 secret key는 노출되면 안되므로 gitignore에 추가한다던지 추가적인 설정이 필요합니다.

### 시크릿 키 객체 생성
application.yml에 Base64URL-인코딩 된 byte 배열의 비밀키를 설정했습니다. 이 비밀키는 signWith 메서드의 매개변수로 사용하기 위해 SecretKey 객체로 변환하는 과정을 거칩니다.
```
public Key key() {
        return Keys.hmacShaKeyFor(Decoders.BASE64URL.decode(secretKey));
    }
```
```
//내가 만든 문자열 시크릿 키
// smilegate-company-is-too-far-so-i-want-to-work-from-home-every-other-day

echo 'smilegate-company-is-too-far-so-i-want-to-work-from-home-every-other-day' | base64

// 결과
c21pbGVnYXRlLWNvbXBhbnktaXMtdG9vLWZhci1zby1pLXdhbnQtdG8td29yay1mcm9tLWhvbWUtZXZlcnktb3RoZXItZGF5Cg==
```

### 로그인 프로세스
```mermaid
sequenceDiagram
    Client->>AuthController: POST /v1/auth-service/signin
    note right of Client: [Header]<br>Authorization: 없음
    note right of Client: { <br> "email": "XXX" <br> "password": "XXX" <br> }
    
    AuthController->>+AuthService(signIn): 로그인 요청
    note right of AuthController: class SignInRequestDTO {<br>String email<br>String password<br>}

    box JWT 토큰 발급
        participant UserService(signIn)
        participant RDBMS
        participant JwtUtils
    end
    
    AuthService(signIn)->>+RDBMS: 유저정보 조회 요청<br>(ReadOnly Transactional)
    RDBMS-->>-AuthService(signIn): 유저 엔티티 응답
    note right of AuthService(signIn): class UserEntity { ... }

    AuthService(signIn)->>+JwtUtils: 토큰 발급 요청
    JwtUtils-->>-AuthService(signIn): HttpOnly Cookie에 유저 ID 가 담긴 토큰 발급
    note over RDBMS: [Payload]<br>userId = 1 <br>

    
    JwtUtils->>Cache: Refresh Token 저장
	  note right of JwtUtils: key = {userId}<br>value = {Refresh Token}

    AuthService(signIn)-->>-AuthController: 로그인 응답
    note right of AuthController: [Header]<br>Cookie: <br>soy-access-jwt="xxxxx" <br> soy-refresh-jwt="xxxxx"
    note right of AuthController: class UserAndTokenResponseDTO { <br>Long userId<br>String nickname<br> String accessToken <br> String refreshToken <br> }

    AuthController-->>Client: 컨트롤러 응답
   note left of AuthController: { <br>"userId": 1, <br> "nickname": "XXXXXXXX", <br> "accessToken": "XXXXXXXX", <br> "refreshToken": "XXXXXXXX" <br> }
```

### 로그아웃 프로세스
```mermaid
sequenceDiagram
Client->>AuthController: POST /v1/auth-service/signout
note right of Client: [Header]<br>Authorization: 없음 <br> Cookie: <br>soy-access-jwt="xxxxx" <br> soy-refresh-jwt="xxxxx"

AuthController->>+AuthService(signOut): 로그아웃 요청

AuthService(signOut)->>+JwtUtils: 토큰 삭제 요청
    
JwtUtils->>Cache: Refresh Token 삭제
note right of JwtUtils: key = {userId}

AuthService(signOut)-->>-AuthController: 로그아웃 응답

AuthController-->>Client: 컨트롤러 응답



```

### Refresh Token을 UUID로 한 이유
- Refresh Token 도 JWT로 관리하면 토큰 자체에서 만료시간을 관리하므로 별도의 DB를 사용하지 않아도 됩니다. 하지만 Access Token, Refresh Token이 둘 다 탈취당하는 경우 Refresh Token을 강제로 만료시킬 수 있는 방법이 없습니다.
- DB에 저장하면 Refresh Token을 삭제하면 되므로 인증 실패 처리를 할 수 있습니다. Refresh Token은 토큰 자체에 데이터를 담을 필요가 없고 Access Token을 재발급하는데만 사용되는 용도이므로 UUID를 사용하는 것이 좋습니다.
https://stackoverflow.com/questions/73823170/refresh-tokens-stored-as-uuid-or-jwt

### Refresh Token이 탈취당하면?
- revoking access of all users by deleting all the refresh tokens when any such malicious behavior is reported → 근데 not reported 되는 경우는?
- Access Token을 재발급할 때마다(새로 로그인하는 경우) Refresh Token도 재발급 및 이전의 Refresh Token은 DB에서 삭제합니다.
- 원래 redis(inmemory db)에 Refresh Token을 저장할 때 **시간복잡도 (O(1))**을 위해 key: refresh token, value: id로 설정했습니다.
- key: refresh token, value: id 인 경우  Refresh Token을 재발급할때마다 같은 유저라도 key 값이 다르기 때문에 Refresh Token이 계속 쌓이게 됩니다. 따라서 이전 refresh token도 expired 되기 전까지 사용 가능한 문제가 발생합니다. 이를 방지하기 위해서는 Refresh Token을 저장하기 전에 id가 존재하는지 확인하면 되는데 id가 value 값이므로 시간복잡도가 엄청나게 증가하게 됩니다.
- key: id, value: refresh token인 경우 같은 id이면 refresh token은 갱신이 됩니다. 또한 redis에서 값을 get할 때 먼저 토큰을 파싱해서 id 값 빼내고 get(id) 하면 refresh token 값 가져올 수 있습니다. 두 방식을 코드로 구현하면 다음과 같은 차이점이 있습니다.
    - key: refresh token, value: id 였을때는 쿠키에서 refreshtoken만 빼오고 바로 redis에서 key값으로 삭제할 수 있습니다.
    - ![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/c01b9144-8722-4e3e-be66-1f2b8e7d6ada)
    - key: id, value: refresh token 이면 Jwts를 parseBuilder 해야 하긴 합니다. 그래도 이 방법이 더 나은 듯 합니다.
    - ![image](https://github.com/sgdevcamp2023/sgwannabe/assets/77220123/6a9797f0-03f6-4087-9f62-b3702f519bb1)

> ### 블랙리스트 도입
> <ul>
> <li>로그아웃 시 클라이언트 헤더에 담긴 토큰은 삭제되어도 서버에서는 유효시간만큼 해당 토큰으로 접근이 가능합니다.</li>
> <li>만약 만료되기 전의 Access Token이 탈취당한다면 보안 문제가 발생하게 됩니다.
> <ul>
> <li>블랙리스트 개념 도입으로, 유저가 로그아웃할 경우 Access Token의 남은 유효시간만큼 Redis에 유효시간을 설정해 블랙리스트에 등록합니다.</li>
> </ul>
> </li>
> <li>AccessToken이 Blacklist에 있을 경우 클라이언트의 로그인 요청은 실패로 처리합니다.</li>
> </ul>
> 
블랙리스트는 고려하지 않기로 결정했습니다.

### 이외 고려 사항들 (Other Considerations)
인증 서버에 추가적으로 로그아웃, 액세스 토큰 재발급, 정상 회원인지 검증하는 기능을 추가할 예정입니다.

### 마일스톤 (Milestones)

1/14~: 개발 시작
1/16: 개발 완료

**Comment by kor-Chipmunk** [comment]
@happysoy 보안까지 꼼꼼하게 신경 쓴 인증이네요! 저도 많이 배웠습니다!

[블랙 리스트를 구현한 블로그](https://medium.com/@choubeyayush4/securing-node-js-applications-with-jwt-refresh-tokens-and-redis-80ffbb54285a)를 보았는데, 소연님과 다른 점이 있더라고요.
`Refresh Token`을 레디스에 저장하지 않는다는 점인데요.
로그아웃할 때 `Access Token` 뿐 아니라 `Refresh Token` 까지 블랙리스트에 저장하더라고요.
따라서 로그인할 때 레디스 통신이 없고 토큰 발급(CPU 연산)만 이뤄집니다.
대신 토큰을 리프레쉬하는 API 를 호출할 때 블랙리스트인지 확인하는데요.
방법마다 어떤 장단점이 있고, 어떤 게 더 Redis 와의 통신을 줄일 수 있을까요?
추가로 인증과 관련한 지점 (로그인, 인증 필터, 로그아웃, 재발급 API) 은 사람들이 어디에 더 호출을 많이 할까요?

추가로 소연님이 설명하신, 블랙리스트를 확인하는 인증 지점 중, 토큰을 확인하는 필터(또는 미들웨어)에도 블랙리스트 로직이 들어가는 걸까요?
로그인은 막을 수 있으나, 블랙리스트 처리된 토큰을 헤더에 기입하여 실제 API 를 호출하는 경우에도 레디스랑 통신하는지 궁금합니다.

---

정리하자면 다음과 같습니다.

| 방법 | 지점 | Redis 연산 (최대) |
| --- | --- | --- |
| 소연 | 로그인 | 1 (`Refresh Token` 저장) |
| | 인증 필터 | 미정  |
| | `Refresh Token` 재발급 | 2 (`Refresh Token` 블랙리스트 조회, 재발급 저장) |
| | 로그아웃 | 2 (`Refresh Token` 삭제, 블랙 리스트 저장) |
| | 총합 | 5 + 미정 |
| 블로그 | 로그인 | 0 ( CPU 연산으로 토큰만 발급 ) |
| | 인증 필터 | 1 (`Access Token` 블랙리스트 확인) |
| | `Refresh Token` 재발급 | 1 ( `Refresh Token` 블랙 리스트 확인 ) |
| | 로그아웃 | 2 ( `Access Token` & `Refresh Token` 블랙 리스트 저장 |
| | 총합 | 4 |

**Comment by kor-Chipmunk** [comment]
@happysoy 오늘 오전에 캠프장님께 한 번 피드백 받았어요.

결론적으로 말하자면, 보안 쪽인 블랙리스트는 고려하지 않아달라, 였어요.
정상적인 플로우로 프론트에서 로그아웃 하면 무사히 액세스 토큰이랑, 리프레쉬 토큰이 삭제된다고 가정을 해서
에너지를 다른 곳에 투자하는 게 낫다는 의견을 주셨어요.

자체로 유효기간이 있는 Refresh Token 을 레디스에 저장하는 게 의미가 있는가, 에 대한 질문으로는
레디스를 써봐서 비교해본다는 것 자체에 의의를 두는 게 좋을 것 같다고 전달 받았는데요.
예전에는 토큰을 JWT 말고 직접 만들어서 액세스 토큰이랑 리프레쉬 토큰을 레디스에 넣고 관리하는 쪽으로 지도를 했다고 하셨는데,
JWT 써도 상관없다고 하시네요.
