### ISSUE TITLE
feat: 프로필 화면을 구현합니다.

### ISSUE THREAD

**Issue by mingzooo** [sgdevcamp2023/sgwannabe#30]
### 요약 (Summary)

프로필 화면을 구현합니다.

### 배경 (Background)

프로필 화면에서 프로필 이미지를 업로드하고, 플레이리스트 피드를 볼 수 있는 화면을 제공하기 위해 구현합니다.

### 목표 (Goals)

- 화면 퍼블리싱
- 이미지 파일 업로드 (파일 서버 통신 이전의 과정까지만)

### 목표가 아닌 것 (Non-Goals)

- 파일 서버 통신
- API 통신

### 계획 (Plan)

피그마의 아래 화면을 기반으로 만들 예정입니다.
<img width="994" alt="image" src="https://github.com/sgdevcamp2023/sgwannabe/assets/62490238/c8ef70b7-164c-4d63-87c5-798f5a6e438b">

### 마일스톤 (Milestones)

~1/16: 프로필 화면 구현 및 pr 올리기

**Comment by kor-Chipmunk** [comment]
#31 PR 머지되어서 이슈 닫겠습니다.
