### ISSUE TITLE
feat: 회원정보를 수정하는 기능을 추가합니다.

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#33]
## 요약 (Summary)

- 회원은 비밀번호를 변경할 수 있습니다.
- 회원은 프로필을 수정할 수 있습니다.

## 배경 (Background)

- 회원가입 시 프로필 이미지를 등록하는 과정이 없기 때문에 기본 이미지로 설정됩니다. 따라서 프로필을 변경할 수 있는 기능이 필요합니다.
- 비밀번호를 변경 기능은 추후 비밀번호 찾기 기능 또한 도입된다면 활용될 수 있습니다.

## 목표 (Goals)

- 비밀번호 변경 시 DB에 저장된 회원 정보 중 비밀번호 부분만 변경합니다.
- 프로필 변경 시 DB에 저장된 회원 정보 중 프로필 부분만 변경합니다.

## 목표가 아닌 것 (Non-Goals)

프로필 설명 추가나 프로필 history 조회 등 서비스 차원의 부가적인 기능들은 고려하지 않습니다. 따라서 profile을 DB에 json 형태로 저장 시 key는 url과 updated_at으로만 저장됩니다.

### 프로필 이미지 등록 및 저장은 어떻게?
파일서버, 유저서버, 프론트 이렇게 역할이 분리되어 있을 때 두가지 방안으로 구현할 수 있습니다.

1. 프론트에서 파일 서버에 직접 접근
    1. pros: 프론트와 파일 서버 간 직접 통신 → 유저 서버와의 통신이 덜 발생
    2. cons: 보안적인 측면? 클라이언트에게 파일 서버의 URL이 노출된다?
2. 프론트를 통해 유저 서버에서 파일 서버에 접근
    1. pros: 보안 이점
    2. cons: 파일을 업로드하면서 발생하는 부하와 대역폭이 유저 서버에서 발생 → 유저 서버 부하

후자의 경우 서버의 cost가 크게 발생한다는 극명한 단점이 있습니다. 따라서 프론트에서 파일 서버로 직접 업로드 요청을 보내고, 프론트가 받아온 URL을 유저 서버로 보내는 로직으로 결정하였습니다.

### 시퀀스 다이어그램
```mermaid
sequenceDiagram
    Client->>UserTokenFilter: POST /password-change
    note right of Client: [Header]<br>Authorization: Bearer <br> AccessToken
    note right of Client: { <br> "password": "xxx" <br> }
    note right of UserTokenFilter: JWT 헤더 있음
    note right of UserTokenFilter: {user info, authorities}

    
    UserTokenFilter->>UserController:컨트롤러 요청
    UserController->>+UserService(changePassword): 비밀번호 변경 요청
    note right of UserController: class PasswordChangeRequestDTO {<br>String password<br>}

		UserService(changePassword)->>RDBMS: 유저정보 변경 요청 <br> Transactional
		
		UserService(changePassword)-->>-UserController: 비밀번호 변경 응답
		note left of UserService(changePassword): class SuccessMessageResponseDTO { <br> String message <br> }
 
		UserController-->>Client: 컨트롤러 응답
		note over UserTokenFilter: { <br> "message": "비밀 번호 변경 성공" <br> }
```

## 이외 고려 사항들 (Other Considerations)
인증, 인가 실패 처리를 위한 필터를 먼저 구현한 뒤 해당 작업을 진행합니다. 만약 비밀번호 변경을 요청해오는 경우 토큰을 검증하는 과정이 선행되어야 하기 때문입니다.

## 마일스톤 (Milestones)

1/16: 테크스펙 작성

**Comment by kor-Chipmunk** [comment]
@happysoy 시퀀스다이어그램의 `/tokens` 주소가 비밀번호를 변경하는 엔드포인트일까요?

**Comment by kor-Chipmunk** [comment]
프론트에서 파일 서버랑 통신한다는 점 인지했습니다!

**Comment by suakang17** [comment]
이상적인 테크스펙인 것 같아요 👍
작업 계획을 한 눈에 이해할 수 있어서 좋습니다

**Comment by happysoy** [comment]
앗 /tokens 엔드포인트 잘못 적었습니다. 수정하도록 하겠습니다!
