### ISSUE TITLE
feat: 인증 서버/ 유저 서버 리팩토링을 진행합니다

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#60]
### 요약 (Summary)

- Sonarlint 플러그인 사용하여 리팩토링을 진행합니다.

### 배경 (Background)

- 작성한 코드의 버그, 보안 취약성, 코드 커버리지, 코드 복잡도 등을 확인합니다.

### 목표 (Goals)

- 코드의 품질과 가독성을 향상시킵니다.
- DB를 로컬 h2에서 MySQL로 변경합니다. MySQL은 도커 이미지를 사용합니다.

### 목표가 아닌 것 (Non-Goals)

- None

### 계획 (Plan)

- Sonarqube를 도커 혹은 로컬에 다운받아 코드를 빌드하는 방식도 있지만 코드 정적 분석만 진행하기 위해 IntelliJ에 Sonarlint 플러그인을 설치하는 방식을 택했습니다.

  
### 이외 고려 사항들 (Other Considerations)
브랜치를 변경하지 않고 기존 브랜치에서 코드 변경을 진행했기 때문에 PR시 브랜치 번호가 맞지 않습니다.

### 마일스톤 (Milestones)

2/5: 소나큐브 도커 설치 및 코드 개선

**Comment by kor-Chipmunk** [comment]
작업 된 것 같아서 이슈 닫겠습니다!
