### ISSUE TITLE
feat: 유저 서버 MySQL 데이터 추가 및 프론트와 연동

### ISSUE THREAD

**Issue by happysoy** [sgdevcamp2023/sgwannabe#71]
### 요약 (Summary)

- MySQL에 데이터를 추가합니다
- 프론트엔드에서 로그인을 확인합니다.

### 배경 (Background)

- 회원가입 과정을 생략하기 위해 MySQL에 테스트 데이터를 저장해놓습니다.

### 목표 (Goals)

- 유저 서버와 Docker의 MySQL 연동
- 회원데이터 sql 문 추가
- 유저 서버 회원정보 조회 API 추가

### 계획 (Plan)

- 회원정보 조회 API에서는 

### 마일스톤 (Milestones)

2/14: 테크스펙 작성

**Comment by kor-Chipmunk** [comment]
작업 된 것 같아서 이슈 닫겠습니다!
