### ISSUE TITLE
feat: Elasticsearch를 활용한 기본 검색 서버를 구축합니다.

### ISSUE THREAD

**Issue by suakang17** [sgdevcamp2023/sgwannabe#9]
### 요약 (Summary)

곡, 아티스트, 사용자, 플레이리스트 명에 대한 검색 서버를 구축합니다.

### 배경 (Background)

사용자가 원하는 리소스에 간편하게 접근하기 위함입니다.

### 목표 (Goals)

- 개발 환경 일치 위해 도커 환경을 구축합니다.
- Elasticsearch를 연결합니다.
- Elasticsearch를 DB로써 활용합니다.
- 단순 검색 요청, 응답을 위한 API를 작성합니다.
- 단순 검색 쿼리를 구현합니다.

### 목표가 아닌 것 (Non-Goals)

- 검색어 입력시 인기 검색어 순으로 정렬된 자동완성 검색 기능 (v2의 범위이므로 제외합니다.)
- 교정 기능: 사용자가 검색어를 잘못 입력했거나 검색 결과가 없을시 도큐먼트 내 존재하는 단어를 대상으로 유사 키워드를 제안하는 교정 기능
- 검색 히스토리 (v2의 범위이므로 제외합니다.)
- 캐싱

### 계획 (Plan)

1. **FastAPI 프로젝트 설정:**
    - FastAPI를 설치하고 프로젝트를 설정합니다.
    
    ```bash
    pip install fastapi
    pip install uvicorn
    
    ```
    
2. **Elasticsearch 설정: → Docker Image 사용**
    - Elasticsearch Python 클라이언트인 `elasticsearch` 또는 `elasticsearch-dsl`을 설치합니다.
    - Docker를 사용하여 FastAPI 및 Elasticsearch를 컨테이너로 배포합니다.
    
    ```bash
    docker-compose up
    ```
    
3. **Elasticsearch에 데이터 색인:**
    - 검색할 데이터를 Elasticsearch에 색인합니다. 자동완성 및 인기 검색어를 위한 필드를 구성합니다.
4. **FastAPI 엔드포인트 작성:**
   - FastAPI에서 Elasticsearch에 쿼리를 보내는 엔드포인트를 작성합니다.
   - 쿼리 결과를 반환하는 엔드포인트를 생성합니다.
   - FastAPI의 Depends를 사용하여 Elasticsearch 연결을 관리합니다.
   ```python
   from fastapi import FastAPI, Depends, HTTPException
   from elasticsearch import Elasticsearch

   app = FastAPI()

   @app.get("/autocomplete/{query}")
   def autocomplete(query: str, es: Elasticsearch = Depends(get_elasticsearch)):
       # Elasticsearch에서 자동완성 및 인기 검색어를 쿼리하여 반환하는 로직 작성
       pass

   def get_elasticsearch():
       # Elasticsearch 연결을 설정하고 반환하는 함수 작성
       pass

   ```
### 이외 고려 사항들 (Other Considerations)

No response

### 마일스톤 (Milestones)

~1/8 개발 환경 구축, Elasticsearch 연결, Client - FastAPI API 명세 작성
~1/9 API 명세 수정, DB설정
~1/10  Elasticsearch 데이터 색인 설정, Client - FastAPI 엔드포인트 작성
~1/11 FastAPI to Elasticsearch 쿼링 엔드포인트 작성

**Comment by kor-Chipmunk** [comment]
@suakang17 
확인했어요! 도커로 엘라스틱 서치를 띄우고 쿼리 검색만 가능하게끔 하는 작업 범위도 좋아 보여요~
아무래도 엘라스틱 서치가 모두에게 생소하다보니, 간략하게 소개하고, 원리가 무엇이고, 쿼리 결과가 어떻게 해석되어야 하는지도 알려주는 문서도 있으면 좋을 것 같아요.
질문사항으로는 엘라스틱서치에서 영어 분석과 한글 분석이 다른 것 같은데, 이 경우도 어떻게 반영이 되는건지도 궁금하네요.

**Comment by suakang17** [comment]
@kor-Chipmunk 작업 범위에 대한 리뷰 감사합니다! 저에게도 가장 생소한 기술이라 공부하며 정리하고 있는데, 저희 프로젝트에 적용되는 부분 위주로 좀 더 다듬어 공유해보겠습니당

한국어의 경우에는 보통 추가적으로 [노리 형태소 분석기](https://www.elastic.co/kr/blog/nori-the-official-elasticsearch-plugin-for-korean-language-analysis)를 적용하는데, 엘라스틱 서치에 공식적으로 지원되고 있고, 공백 기준으로 구분하는 영어와 달리 형태소 단위로 파싱해 분석한다고 합니다. 해당 내용도 위의 엘라스틱 서치 소개문서에 포함하겠습니다~~
